Create model and migration Slider
alkemyTech/OT247-Node pull request #16
Opened 2022-07-16 03:03 UTC by AlexAc0226

Link ticket: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-29

**Description**
COMO usuario administrador
QUIERO gestionar las imágenes
PARA modificar eficientemente el contenido visual

Criterios de aceptación:
Los Slides de la pantalla de inicio serán gestionados de forma dinámica por el administrador del sitio. Los mismos tendrán como campos imageUrl, text, order y organizationId (ya que pertenecerán una ong)

**Evidence**
![image](https://user-images.githubusercontent.com/88632261/179336775-b3d4fefc-5bb6-46af-be66-c51aa470cf1d.png)

2022-07-16 21:21 UTC, NicolasPreiti requested changes
Los archivos tienen el nombre slider cuando el ticket pide slides

2022-07-16 21:21 UTC, NicolasPreiti commented on models/slider.js
> +    modelName: 'Slider',
falta timestamps: true

2022-07-18 05:01 UTC, rodrigotonso commented
El título del PR hace referencia a model & migrations

2022-07-18 05:06 UTC, rodrigotonso requested changes

2022-07-18 05:06 UTC, rodrigotonso commented on models/slide.js
> +    timestamp: true,
Es buena práctica (ademas de que es lo que venimos haciendo) hacer un soft-delete salvo que se haya plateado la estrategia contraria

2022-07-18 15:44 UTC, AlexAc0226 commented on models/slide.js
> +    timestamp: true,
Added...

2022-07-18 21:42 UTC, rodrigotonso approved these changes

2022-07-18 21:49 UTC, NicolasPreiti approved these changes

2022-07-19 01:31 UTC, merged