Endpoint de autenticación
alkemyTech/OT247-Node pull request #20
Opened 2022-07-19 12:33 UTC by RamosGabriel2

Link Ticket: https://alkemy-labs.atlassian.net/browse/OT247-25

**Descripción**

COMO usuario
QUIERO loguearme en el sistema
PARA acceder a sus funcionalidades

Criterios de aceptación:

Se debe hacer una petición de tipo POST /auth/login 
Deberá validarse el envío y el tipo de dato de los campos email y password en la petición, y desencriptar la contraseña para autenticarse

- Validar email y password en petición
- Verificar si existe usuario con el email solicitado
- Si existe, comparar contraseña encriptada con contraseña enviada en petición
- Devolver al usuario en el caso de que exista y la contraseña sea válida, en el caso de que ocurra un error, devolver {ok: false}

**Evidencia**

![image](https://user-images.githubusercontent.com/99927685/179750012-fa9554e5-ea91-4f65-810e-14ae511d5b27.png)

![image](https://user-images.githubusercontent.com/99927685/179750968-fcbd2c16-8c79-47ad-9a04-985db4d3e2ac.png)

Observación: Se agrego el archivo login.ejs en la carpeta de views con el fin de realizar pruebas, puede ser eliminado.

2022-07-20 02:44 UTC, AlexAc0226 commented on controllers/users.js
> +const { User } = require('../models');
El modelo se debe importar aqui, se debe importar en los servicios

2022-07-20 02:49 UTC, AlexAc0226 commented on controllers/users.js
> +const { validationResult } = require('express-validator');
La funcion validationResult  se deberia realizar en un fichero dentro de una carpeta "helpers"

2022-07-20 02:52 UTC, AlexAc0226 commented on controllers/users.js
> +}
Gran parte de este fragmento de codigo se debe realizar en los servicios, solo las respuesta que se devuelven irian en este fichero

2022-07-20 02:54 UTC, AlexAc0226 commented on models/organization.js
> +  return Organization;
Se deberia hacer una rama fix para solucionar inconvenientes que estan fuera del scoop de esté ticket

2022-07-20 02:57 UTC, AlexAc0226 commented on routes/index.js
> +});
Deberia estar en el fichero auth, carpeta routes

2022-07-20 03:00 UTC, AlexAc0226 commented on routes/auth.js
> +const {authUser} = require('../controllers/users');
El nombre de la funcion importada debe ser más y/o mejor descriptivo con relacion a su correspondiente funcionamiento. Ej: userLogin, o algo asi

2022-07-20 03:01 UTC, AlexAc0226 requested changes
Revisar detalles marcados...

2022-07-20 04:51 UTC, rodrigotonso requested changes

2022-07-20 04:51 UTC, rodrigotonso commented on controllers/users.js
> +const { validationResult } = require('express-validator');
O en un middelware junto a las validaciones

2022-07-20 04:51 UTC, rodrigotonso commented on controllers/users.js
> +    const userFinded = await User.findOne({ where: {email: Email}});
Es probable que se lleve este código a otro archivo en caso de no ser asi lo comun es validar en la linea siguiente a la petición y realizar un Fail Fast, sería solo un if con un return de lo que queres

PD: Intentar siempre responder un JSON (Ver REST)

2022-07-20 04:51 UTC, rodrigotonso commented on models/organization.js
> +  return Organization;
En empresas grandes puede ser que te pidan total apego a la tarea y los fix por separado
En empresas chicas fix menores pueden repararse en el mismo PR intentar en la proxima en un commit único.

2022-07-20 04:51 UTC, rodrigotonso commented on routes/auth.js
> +const {authUser} = require('../controllers/users');
El título de la tarea fue medio tramposo pero es cierto se esta haciendo un login

2022-07-21 13:00 UTC, RamosGabriel2 commented on models/organization.js
> +  return Organization;
Corregido

2022-07-21 13:00 UTC, RamosGabriel2 commented on routes/auth.js
> +const {authUser} = require('../controllers/users');
Nombre de función corregido

2022-07-21 13:01 UTC, RamosGabriel2 commented on controllers/users.js
> +    const userFinded = await User.findOne({ where: {email: Email}});
Corregido

2022-07-25 06:08 UTC, RamosGabriel2 commented on controllers/users.js
> +const { User } = require('../models');
corregido

2022-07-25 06:14 UTC, RamosGabriel2 commented on controllers/users.js
> +const { validationResult } = require('express-validator');
funcion validationResult removida

2022-07-25 06:15 UTC, RamosGabriel2 commented on controllers/users.js
> +}
Corregido

2022-07-25 06:17 UTC, RamosGabriel2 commented on routes/index.js
> +});
Esta ruta corresponde a una vista que se uso con el fin de probar los valores enviados por el usuario, el mismo puede ser borrado

2022-07-26 05:43 UTC, rodrigotonso submitted a review, later dismissed

2022-07-27 20:17 UTC, merged