Changed sendgrid script to use template
alkemyTech/OT247-Node pull request #26
Opened 2022-07-20 16:53 UTC by rodrigoacn

[OT247-30](https://alkemy-labs.atlassian.net/browse/OT247-30)
![mail_template](https://user-images.githubusercontent.com/107000658/180039080-5c9a8548-0945-4cdb-b279-89316fefe57d.PNG)

2022-07-20 18:11 UTC, santieb requested changes
A mi parecer habría que crear un objeto que haga referencia al template de bienvenida con los datos de templateId así después podemos llamar a la función sendMail y pasar los datos del template como parámetro para usarlo en diferentes situaciones

2022-07-20 18:11 UTC, santieb commented on services/sendgrid.js
> +const sendMail = async ({ email, subject, sandboxMode = false }) => {
Habría que pasar como parámetro el template id y dynamic_template_data así podemos utilizar esta función en diferentes situaciones

2022-07-20 18:11 UTC, santieb commented on services/sendgrid.js
> +  	const user = await userController.findUserByEmail(email)
Estos datos del usuario lo podemos obtener directamente de la request de registrar usuario, por ahi nos podríamos ahorrar la consulta

2022-07-24 23:51 UTC, rodrigotonso commented on mail-templates/mail-templates.js
> +	  city: user.lastName
¿city: lastName?

2022-07-26 05:45 UTC, rodrigotonso submitted a review, later dismissed

2022-07-27 20:24 UTC, merged