OT247-38 | ENDPOINT: update public data of an organization by admin
alkemyTech/OT247-Node pull request #29
Opened 2022-07-21 23:17 UTC by NicolasPreiti

Ticket link: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-38

Description:

COMO usuario administrador
QUIERO actualizar los datos públicos de la Organización
PARA mantener la información actualizada

Criterios de aceptación:
Petición PATCH hacia ruta /organizations/public/:id

Solamente el usuario administrador podrá editar los datos públicos de la Organización. Deberá validar los campos requeridos y el formato correcto de los mismos

Evidence:

![image](https://user-images.githubusercontent.com/99926180/180329914-6b6e3f13-5f49-485c-b3d6-8327530f6e9c.png)
![image](https://user-images.githubusercontent.com/99926180/180330058-f52799eb-bc79-4bd3-91c8-75634b0d7da2.png)
![image](https://user-images.githubusercontent.com/99926180/180330375-d99d7d17-7fd0-4f01-9735-408c79dcd548.png)

2022-07-25 03:25 UTC, rodrigotonso requested changes

2022-07-25 03:25 UTC, rodrigotonso commented on controllers/organization.js
> +      if (!Number.isInteger(Number(id)))
No debería hacerse las validaciones en el controller
Sería mas claro en un middleware

Tambien usaría express-validator (Es la que venimos usando en el proyecto)

2022-07-25 03:25 UTC, rodrigotonso commented on controllers/organization.js
> +      updatedOrganization == 0
La validación es extraña, doble igual ¿? a 0 ¿? unico caso false ¿?

2022-07-26 07:03 UTC, NicolasPreiti commented on controllers/organization.js
> +      if (!Number.isInteger(Number(id)))
Corregido

2022-07-26 07:03 UTC, NicolasPreiti commented on controllers/organization.js
> +      updatedOrganization == 0
Corregido

2022-07-26 22:00 UTC, rodrigotonso approved these changes

2022-07-26 22:00 UTC, rodrigotonso commented on controllers/organization.js
> +        ? res.status(404).json({ status: 404, message: 'Organization not found' })
Es raro estar pasando dos veces el status (no es tan raro en realidad pero si se encara así lo que termina pasando es que se filtran respuestas con status 403 y 422 al mismo tiempo y cosas así)
Si es que queremos estipular ese tipo de respuesta ya podríamos hacer un método espacial para eso (creo que ya se hizo) sino con una sola vez debería ir

2022-07-26 23:49 UTC, merged