[USER] Ot247 17 - Model, migration and controller User
alkemyTech/OT247-Node pull request #3
Opened 2022-07-13 16:47 UTC by AlexAc0226

Descrition:
id: INTEGER NOT NULL AUTO_INCREMENT
firstName: VARCHAR NOT NULL
lastName: VARCHAR NOT NULL
email: VARCHAR UNIQUE NOT NULL
password: VARCHAR NOT NULL
photo: VARCHAR NULLABLE
roleId: Clave foranea hacia ID de Role
timestamps y softDeletes

**Evidence**
![image](https://user-images.githubusercontent.com/88632261/178787303-89ff6c73-6ed1-4ba5-ba88-281efd059342.png)

2022-07-13 19:21 UTC, RamosGabriel2 requested changes
carpeta database no necesario

2022-07-13 19:40 UTC, RamosGabriel2 approved these changes, later dismissed

2022-07-13 19:43 UTC, santieb approved these changes
bien

2022-07-13 20:36 UTC, santieb submitted a review, later dismissed

2022-07-13 22:27 UTC, rodrigotonso requested changes

2022-07-13 22:27 UTC, rodrigotonso commented on models/user.js
>      deletedAt: DataTypes.DATE
Choca con paranoid: true
https://sequelize.org/docs/v6/core-concepts/paranoid/

2022-07-13 22:27 UTC, rodrigotonso commented on models/user.js
> +      User.hasMany(models.Comment, { foreignKey: 'user_id' })
Por que la relación a comment en este PR ¿?

2022-07-13 22:27 UTC, rodrigotonso commented
Extra reviews
Se creó el archivo controllers/users.js vacío ¿?
Se eliminó la migration create-role, la tarea no involucraba nada sobre los roles.
Se eliminó el model role, la tarea no involucraba nada sobre los roles.

2022-07-13 22:33 UTC, rodrigotonso commented
Por fa, dejemos el link al ticket al inicio del PR
https://alkemy-labs.atlassian.net/browse/OT247-17

2022-07-13 22:56 UTC, rodrigotonso commented on migrations/20220713153211-create-user.js
>        },
Vamos a mantenernos todos con upperCamel por que veo que es como se viene trabajando

2022-07-13 22:57 UTC, rodrigotonso commented on models/user.js
>      deletedAt: DataTypes.DATE
Vamos a mantenernos todos con upperCamel por que veo que es como se viene trabajando

2022-07-13 23:29 UTC, AlexAc0226 commented on models/user.js
>      deletedAt: DataTypes.DATE
Cambio realizado...

2022-07-13 23:57 UTC, AlexAc0226 commented on models/user.js
>      deletedAt: DataTypes.DATE
Corregido...

2022-07-13 23:58 UTC, AlexAc0226 commented on models/user.js
> +      User.hasMany(models.Comment, { foreignKey: 'user_id' })
Ya quedo...

2022-07-14 18:24 UTC, rodrigotonso approved these changes

2022-07-14 18:55 UTC, merged