Endpoint de Actualizar Usuario
alkemyTech/OT247-Node pull request #30
Opened 2022-07-21 23:22 UTC by santieb

COMO usuario 
QUIERO actualizar mis datos
PARA modificar mi perfil

Criterios de aceptación:

PATCH a /users/:id. En el caso de que el usuario no exista, devolverá un error 404.

Se debe verificar que el usuario que esta realizando la petición sea el mismo que se busca modificar.

2022-07-21 23:25 UTC, santieb commented on controllers/users.js
> +// const welcomeMail = require('../mail-templates/mail-templates')
A esto lo comente ya que falta que se mergee el pr del template

2022-07-25 03:43 UTC, rodrigotonso requested changes

2022-07-25 03:43 UTC, rodrigotonso commented on controllers/users.js
> +      if (Number(id) !== userId)
Estaría bueno hacerle middleware a esto

2022-07-25 03:43 UTC, rodrigotonso commented on controllers/users.js
> +      if (!firstName && !lastName && !photo)
Estaría bueno hacerle middleware a esto

2022-07-25 03:43 UTC, rodrigotonso commented on controllers/users.js
> +      if (!firstName && !lastName && !photo)
expressvalidator

2022-07-25 03:43 UTC, rodrigotonso commented on middlewares/userExists.js
> +    const user = await User.count({ where: { id } })
findOne no sería mas apropiado???

2022-07-26 11:56 UTC, santieb commented on controllers/users.js
> +      if (Number(id) !== userId)
Lo valide dentro del schema de express validator, estaría bien?

2022-07-26 12:01 UTC, santieb commented on middlewares/userExists.js
> +    const user = await User.count({ where: { id } })
Vi que era el método que mas se asemeja al comportamiento de exists de mongoose que hablamos el otro día. Ahi le puse findOne por que quedaba un poco confuso

2022-07-27 20:26 UTC, merged