List categories names
alkemyTech/OT247-Node pull request #33
Opened 2022-07-22 21:16 UTC by rodrigoacn

[OT247-41](https://alkemy-labs.atlassian.net/browse/OT247-41)
![categories_names_error](https://user-images.githubusercontent.com/107000658/180569627-61f8925a-c015-4911-abd0-8219b24795e6.PNG)
![categories_names_success](https://user-images.githubusercontent.com/107000658/180569648-ba56141e-e280-4f88-aadf-d360552ef87c.PNG)

2022-07-24 19:45 UTC, javiboin requested changes

2022-07-24 19:45 UTC, javiboin commented on seeders/create-categories.js
> +     * await queryInterface.bulkDelete('People', null, {});
Podes agregar esta linea con el nombre de la tabla para eliminarla en caso de querer revertir la migración.

2022-07-25 04:46 UTC, rodrigotonso approved these changes

2022-07-26 05:46 UTC, rodrigotonso submitted a review, later dismissed

2022-07-27 20:31 UTC, merged