[ENDPOINT] OT247-44 Update Categories
alkemyTech/OT247-Node pull request #34
Opened 2022-07-23 01:37 UTC by AlexAc0226

Link ticket: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-44

**Description**
Descripción

COMO usuario administrador
QUIERO modificar una categoría existente
PARA mantener la información actualizada

Criterios de aceptación:
PUT /categories/:id - Deberá validar que la categoría existe y actualizarla si hiciera falta, caso contrario devolver un error
Solo usuario administrador debe poder hacerlo

**Evidence**
New category
![image](https://user-images.githubusercontent.com/88632261/180585318-8f8fb8d5-6f0f-49b4-96e8-3d2a85ebd299.png)

Category added to DB
![image](https://user-images.githubusercontent.com/88632261/180585338-081d2096-5846-42d7-bb11-efb56b7a795a.png)

Updated category by ID
![image](https://user-images.githubusercontent.com/88632261/180585360-8f7c9ee3-99fc-4499-915e-b5b40dde9ac2.png)
![image](https://user-images.githubusercontent.com/88632261/180585414-ff555074-d5cd-4b3d-b2b6-ea4f080334de.png)

Updated DB
![image](https://user-images.githubusercontent.com/88632261/180585434-e1131288-a3bd-42a9-b724-1954eb148299.png)

ID category not found
![image](https://user-images.githubusercontent.com/88632261/180585460-f98332e3-fbd6-4e4a-929d-4eff04ebeefc.png)

2022-07-23 02:22 UTC, santieb commented on services/category.js
> +            throw new ErrorObject(404, 'Category not found')
Como propuesta por ahi podríamos hacer un middleware que valide si la categoría existe, ya que vamos a usar el mismo código y lógica para otros endpoints como el de eliminar categoría

2022-07-23 02:22 UTC, santieb reviewed
Fíjate que la tarea dice que hay que actualizar la categoría si hiciera falta, si es para evitar acceder a la base de datos por ahi te convendría hacer una validación de este estilo antes de acceder a los servicios en el caso que no se haya hecho ningún cambio: 

```
      if (!body.name && !body.description && !body.image)
        return res.status(400).json({ msg: 'You have not made any changes' })
```

2022-07-23 02:28 UTC, AlexAc0226 commented on services/category.js
> +            throw new ErrorObject(404, 'Category not found')
> 
En ningun lado del ticket dice que se require verificar que los campos esten vacios o no...

2022-07-23 02:31 UTC, AlexAc0226 commented
> 

En ningun lado del ticket se menciona que se debe verificar que los campos que debe llenar el usuario admin tienen que estar rellenados o no, estaria por fuera del ticket.

2022-07-23 02:54 UTC, NicolasPreiti reviewed
Creo que habían dicho que validemos los datos para evitar hacer consultas innecesarias a la base de datos.

2022-07-25 04:55 UTC, rodrigotonso requested changes

2022-07-25 04:55 UTC, rodrigotonso commented on helpers/existCategory.js
> +            return false;
Si no estamos aclarando el error pondría el return arriba en el category directamente y que devuelva un null en caso de no match

2022-07-25 04:55 UTC, rodrigotonso commented on services/category.js
> +        const updatedCategory = await Category.update({
Creo que ví que comentaron de validar antes
en este punto tenes la const category con todos los datos para comparar si hubo algún cambio, el prevenir consultas innecesarias es util
Pero hay que tener cuidado de no ensuciar el código

2022-07-26 05:47 UTC, rodrigotonso submitted a review, later dismissed

2022-07-27 20:49 UTC, merged