organization model OT247-15
alkemyTech/OT247-Node pull request #5
Opened 2022-07-13 19:48 UTC by santieb

2022-07-13 19:57 UTC, AlexAc0226 requested changes
Falta crear fichero "Organizations" en la carpeta controllers

2022-07-13 22:34 UTC, rodrigotonso commented
Por fa, dejemos link al ticket al comienzo del PR
https://alkemy-labs.atlassian.net/browse/OT247-15

2022-07-14 18:43 UTC, rodrigotonso approved these changes
![image](https://user-images.githubusercontent.com/67134489/179058996-5c8e25b0-6514-44f8-923a-0ef2d3cfc25f.png)

2022-07-14 19:04 UTC, AlexAc0226 approved these changes

2022-07-14 19:09 UTC, merged