Crear modelo, migración y controlador base de Categories
alkemyTech/OT247-Node pull request #6
Opened 2022-07-14 15:37 UTC by RamosGabriel2

Link ticket: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-18

Description:
Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
description: VARCHAR NULLABLE
image: VARCHAR NULLABLE
timestamps y softDeletes

Evidence

![image](https://user-images.githubusercontent.com/99927685/179021169-992b186d-7a55-4122-876d-f0c99e0bab1b.png)

2022-07-14 18:25 UTC, rodrigotonso commented
Se eliminó el .env.example debería reponerse

2022-07-14 18:43 UTC, rodrigotonso requested changes

2022-07-14 18:43 UTC, rodrigotonso commented on views/index.ejs
> +    <h2>titulo de prueba</h2>
Se vino al PR, debería eliminarse

2022-07-14 18:43 UTC, rodrigotonso commented on models/categories.js
> +    modelName: 'Categories',
Deberíamos ponerlo en singular
https://sequelize.org/docs/v6/other-topics/naming-strategies/

2022-07-15 00:06 UTC, RamosGabriel2 commented on views/index.ejs
> +    <h2>titulo de prueba</h2>
Corregido

2022-07-15 00:08 UTC, RamosGabriel2 commented on models/categories.js
> +    modelName: 'Categories',
Corregido

2022-07-16 03:23 UTC, AlexAc0226 approved these changes

2022-07-17 21:38 UTC, rodrigotonso approved these changes

2022-07-18 04:36 UTC, merged