Crear modelo, migración y controlador base de Activities
alkemyTech/OT247-Node pull request #7
Opened 2022-07-14 15:56 UTC by NicolasPreiti

Link Ticket: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-21

Description:
Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
timestamps y softDeletes

controlador base:impot model - export clase

Evidence:
![image](https://user-images.githubusercontent.com/99926180/179025078-3fbbe309-1c47-484c-bd6b-208aa63e0839.png)

2022-07-14 18:44 UTC, rodrigotonso commented
Se eliminó el .env.example debería volverse a agregar

2022-07-14 18:47 UTC, rodrigotonso requested changes

2022-07-14 18:47 UTC, rodrigotonso commented on models/activities.js
> +      },
paranoid: true
timestamps: true

ya les dice al módelo que estan los campos ****ed_at
debería eliminarse la declaración

2022-07-14 21:25 UTC, NicolasPreiti commented on models/activities.js
> +      },
Ya lo corregí.

2022-07-15 12:53 UTC, rodrigotonso approved these changes

2022-07-15 13:10 UTC, merged