OT247-81 | ENDPOINT Create Comment
alkemyTech/OT247-Node pull request #88
Opened 2022-08-08 08:10 UTC by RamosGabriel2

Link ticket: https://alkemy-labs.atlassian.net/browse/OT247-81

Descripción:

COMO usuario
QUIERO dar de alta nuevos Comentarios
PARA agregarlos a un post existente

Criterios de aceptación:

POST /comments - Deberá validar que se envíe el campo newsId, userId y content

Evidencia:

![image](https://user-images.githubusercontent.com/99927685/183370483-2d2db65c-33df-4afd-8a2e-448f86b77a0e.png)

![image](https://user-images.githubusercontent.com/99927685/183370577-0f309733-7fe0-4083-9a46-6d4232899f8a.png)

2022-08-09 14:55 UTC, NicolasPreiti approved these changes, later dismissed

2022-08-12 23:55 UTC, javiboin requested changes

2022-08-12 23:55 UTC, javiboin commented on controllers/comments.js
> +      const newComment = await createNewComment(body);
Acá te convendría usar commentService que ya venia referenciado como es usado en deleteCommentById.
commentService.createNewComment

2022-08-17 14:36 UTC, NicolasPreiti reviewed
Arreglar conflictos

2022-08-17 22:39 UTC, merged