[ENDPOINT]  OT247-24 - Register user
alkemyTech/OT247-Node pull request #9
Opened 2022-07-15 06:14 UTC by AlexAc0226

Link ticket: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-24

**Description**
COMO usuario
QUIERO registrarme en el sistema
PARA ser parte del mismo

Criterios de aceptación:
Se debe hacer una petición POST /auth/register 
El endpoint deberá validar que existe y que el tipo de dato es correcto los campos Nombre, Apellido, Email, Contraseña. 
La contraseña debe ser encriptada. 
Deberá devolver como respuesta el usuario generado.

Validar
Encriptar contraseña
Almacenar en base de datos

**Evidence**
New user registered:
![image](https://user-images.githubusercontent.com/88632261/179161133-66ffb767-97bd-4f52-9b13-0f194ad2fa86.png)

New user added in the DB:
![image](https://user-images.githubusercontent.com/88632261/179161582-0d117073-c030-4fc6-b1d7-48b70ae46aa4.png)

Message error -> Password invalid:
![image](https://user-images.githubusercontent.com/88632261/179161954-177c19e2-37c2-4a24-b62c-9d5a269fff57.png)

Message error -> FirstName and lastName empty:
![image](https://user-images.githubusercontent.com/88632261/179162245-ea719750-0a79-43e7-9de5-5416241001b6.png)

2022-07-18 05:29 UTC, rodrigotonso requested changes

2022-07-18 05:29 UTC, rodrigotonso commented on routes/auth.js
> +router.post("/register", schemaValidator(user), post)
La exportación como post hizo que se llame aca como post y es extraño debería tener un nombre asociado a lo que pertenece y hace

2022-07-18 05:29 UTC, rodrigotonso commented on models/user.js
>       * The `models/index` file will call this method automatically.
Corresponde no modificar algo que esta haciéndese en otro PR o ya se hizo
Hacer el pull de develop actualizado con los cambios de esta tarea
(Entiendo que cuando se arrancó la tarea dependiente no estaba terminada)

2022-07-18 05:29 UTC, rodrigotonso commented on migrations/20220713153211-create-user.js
>          type: Sequelize.INTEGER
Corresponde no modificar algo que esta haciéndese en otro PR o ya se hizo
Hacer el pull de develop actualizado con los cambios de esta tarea
(Entiendo que cuando se arrancó la tarea dependiente no estaba terminada)

2022-07-18 05:29 UTC, rodrigotonso commented on controllers/users.js
> +    post: catchAsync(async (req, res, next) => {
Es raro exportar el objeto sin key declarada con un post hijo, va a hacer poco intuitiva la lectura
Deebería darsele un nombre y exportarlo
Ej
const user = {

}

Es recomendado no usar en declaraciones propias los verbos http, se puede deducir de varios lugares que se usando ese verbo pero no necesariamente la acción (buscar recomendaciones rest)
Cambiar el nombre post a algo que haga referencia a lo que hace el método

2022-07-18 05:29 UTC, rodrigotonso commented on controllers/users.js
> +    post: catchAsync(async (req, res, next) => {
Por que hacemos la lógica de cath async???

2022-07-18 05:29 UTC, rodrigotonso commented on helpers/handleValidator.js
> +    return res.status(403).send({ errors: err.array() })
Parecería más apropiado un 400 (un 422 podría ser tambien) pero un 403 no me suena el estado más representativo

2022-07-18 15:57 UTC, AlexAc0226 commented on controllers/users.js
> +    post: catchAsync(async (req, res, next) => {
Cambios de nombre a userRegister

2022-07-18 16:20 UTC, AlexAc0226 commented on controllers/users.js
> +    post: catchAsync(async (req, res, next) => {
Es una capa mas de proteccion para el controlador, por si algo se pasa por alto en otro middleware y entra a la ruta.

2022-07-20 03:55 UTC, rodrigotonso approved these changes, later dismissed

2022-07-20 15:07 UTC, santieb approved these changes

2022-07-20 15:37 UTC, merged