OT247-82 | Endpoint Actualización Comentarios
alkemyTech/OT247-Node pull request #91
Opened 2022-08-08 23:36 UTC by javiboin

**Ticket**:
https://alkemy-labs.atlassian.net/browse/OT247-82

**Description**:
COMO usuario
QUIERO actualizar un comentario propio
PARA mantener la información actualizada

Criterios de aceptación:
PUT /comments/:id - Deberá validar la existencia del comentario en base a su id. Solamente podrán editar un comentario el usuario que lo realizó o un administrador

**Evidence**:
Postman OK response:
![Postman OK](https://user-images.githubusercontent.com/46333397/183531823-15e81023-be52-474a-aeb3-9f74ae96c3d3.PNG)

Postman Fail not found:
![Postman Fail not found](https://user-images.githubusercontent.com/46333397/183531860-848e7c97-3168-47ad-a59a-60f6d7ba17a3.PNG)

Postman Fail not authorized:
![Postman Fail not authorized](https://user-images.githubusercontent.com/46333397/183531890-5a404415-8dfb-4617-8f33-28c5f44fa0ff.PNG)

Database:
Comments:
![Database Comments Indicate](https://user-images.githubusercontent.com/46333397/183532290-3e9e07c1-8a73-44f8-bb70-426406161f8c.png)

Users:
![Database Users](https://user-images.githubusercontent.com/46333397/183532315-0b411d39-ad63-4219-ae88-92325ec786f7.png)

2022-08-09 00:10 UTC, javiboin commented
Conflictos resueltos

2022-08-09 14:45 UTC, NicolasPreiti commented on migrations/20220716021559-create-slide.js
>          },
Este archivo no corresponde al ticket

2022-08-09 14:45 UTC, NicolasPreiti commented on migrations/20220724191330-create-news.js
>        },
No corresponde al ticket

2022-08-09 14:46 UTC, NicolasPreiti commented on routes/categories.js
>    .get('/:id', isAdmin, categoryCtrl.getCategoryAsAdmin)
no corresponde al ticket

2022-08-09 14:47 UTC, NicolasPreiti requested changes
Ver y quitar archivos que están fuera del ticket

2022-08-09 17:47 UTC, javiboin commented on migrations/20220716021559-create-slide.js
>          },
Esto viene del ultimo commit antes del PR que fueron tareas de refactor que me fui encontrando en el momento. Se encontraron duplicadas estas líneas y las quise  sacar antes de traer algún inconveniente.

2022-08-09 17:47 UTC, javiboin commented on migrations/20220724191330-create-news.js
>        },
Esto viene del ultimo commit antes del PR que fueron tareas de refactor que me fui encontrando en el momento. Se encontraron duplicadas estas líneas y las quise  sacar antes de traer algún inconveniente.

2022-08-09 17:51 UTC, NicolasPreiti commented on migrations/20220716021559-create-slide.js
>          },
claro pero se debería de resolver en un PR aparte

2022-08-09 19:13 UTC, javiboin commented on migrations/20220716021559-create-slide.js
>          },
OK ahi lo saco.

2022-08-09 19:45 UTC, javiboin commented on routes/categories.js
>    .get('/:id', isAdmin, categoryCtrl.getCategoryAsAdmin)
Cambios borrados.

2022-08-09 19:46 UTC, javiboin commented on migrations/20220716021559-create-slide.js
>          },
Cambios Borrados

2022-08-10 19:53 UTC, NicolasPreiti commented on middlewares/isAdmin.js
> +    if (roleId !== 1) return res.status(401).send('[Unauthorized - User] - [Access - Denied]');
los admin no estas asociados con el roleId 2?

2022-08-12 19:14 UTC, javiboin commented on middlewares/isAdmin.js
> +    if (roleId !== 1) return res.status(401).send('[Unauthorized - User] - [Access - Denied]');
Yes,

![image](https://user-images.githubusercontent.com/46333397/184427769-2f563c7f-032a-4494-a8e7-7172ad46036d.png)

2022-08-13 16:43 UTC, NicolasPreiti submitted a review, later dismissed

2022-08-13 17:00 UTC, NicolasPreiti approved these changes

2022-08-13 17:01 UTC, merged