[ENDPOINT] OT247-80 Get for listering comments
alkemyTech/OT247-Node pull request #94
Opened 2022-08-09 23:11 UTC by AlexAc0226

Link ticket:  https://alkemy-labs.atlassian.net/jira/software/c/projects/OT247/boards/337?modal=detail&selectedIssue=OT247-80

**Description**
COMO usuario administrador
QUIERO obtener un listado de Comentarios
PARA moderar los mismo.
Criterios de aceptación:
GET /comments - Devolverá todos los Comentarios, ordenados por fecha de creación, solamente el campo content

2022-08-10 19:56 UTC, NicolasPreiti submitted a review, later dismissed

2022-08-12 23:59 UTC, javiboin approved these changes, later dismissed

2022-08-13 21:02 UTC, NicolasPreiti requested changes

2022-08-13 21:02 UTC, NicolasPreiti commented on routes/comment.js
>  module.exports = router;
Te faltaría adaptar la ruta a como esta en el refactor.

2022-08-13 21:04 UTC, AlexAc0226 commented on routes/comment.js
>  module.exports = router;
Y cual es la nueva forma de escribirlo, porque esta como tu linea de abajo....

2022-08-13 21:10 UTC, NicolasPreiti commented on routes/comment.js
>  module.exports = router;
revísalo en el código de develop, una de las cosas seria la forma de importar los controladores, ahora se importan con el nombre "controller".

2022-08-13 22:15 UTC, NicolasPreiti commented on routes/comment.js
> +const router = require('express').Router();
El router lo generamos por separado de la importación pero te la dejo pasar.

2022-08-13 22:15 UTC, NicolasPreiti approved these changes

2022-08-13 22:25 UTC, AlexAc0226 commented on routes/comment.js
>  module.exports = router;
ya esta resuelto...

2022-08-14 00:07 UTC, merged